"""
apogee.stage5_validation
===========================

The credibility stage. Anyone can build a simulator; what separates a
portfolio/industry-grade project is *validating* it against real flight
data — this is standard Verification & Validation (V&V) methodology used
at every real aerospace company before a simulation is trusted for
mission-critical decisions.

This module ingests a logged flight (apogee, max velocity, descent rate,
flight time — the fields every commercial altimeter, e.g. a PerfectFlite
or Eggtimer, logs by default) and compares it against what RocketPy
predicted for the *same* nominal conditions, producing a signed
percentage error per metric plus a plain-language explanation of likely
error sources — not just a number, but the engineering reasoning behind
it, the way a real post-flight report would.

No hardware flight was flown for this repo (it's a software deliverable),
so ``data/sample_flight_log.csv`` is a clearly-labeled SYNTHETIC demo log
—generated by taking the nominal simulation and applying a small random
perturbation, exactly the kind of residual a real flight typically shows.
Swap in a real logger CSV and this module works unchanged; see the
README section "Using real flight data."
"""

from __future__ import annotations

import csv
from pathlib import Path

from apogee.schemas import FlightLogRecord, ValidationResult

ACCEPTABLE_ERROR_PCT = 8.0


def load_flight_log(csv_path: str | Path) -> FlightLogRecord:
    path = Path(csv_path)
    with open(path) as f:
        row = next(csv.DictReader(f))
    return FlightLogRecord(
        source=row.get("source", path.name),
        apogee_m=float(row["apogee_m"]),
        max_velocity_m_s=float(row["max_velocity_m_s"]),
        descent_rate_m_s=float(row["descent_rate_m_s"]),
        flight_time_s=float(row["flight_time_s"]),
    )


def _pct_error(sim: float, actual: float) -> float:
    if actual == 0:
        return 0.0
    return round(100.0 * (sim - actual) / actual, 2)


def _diagnose(apogee_err: float, velocity_err: float, descent_err: float) -> list[str]:
    causes = []
    if abs(apogee_err) > 3.0:
        direction = "over-predicted" if apogee_err > 0 else "under-predicted"
        causes.append(
            f"Apogee {direction} by {abs(apogee_err):.1f}% — the most common cause is a static "
            "drag coefficient (Cd) in the simulation vs. real surface roughness, paint, and "
            "protruding rivets/rail buttons increasing actual drag on the built airframe."
        )
    if abs(velocity_err) > 3.0:
        causes.append(
            f"Max velocity error of {abs(velocity_err):.1f}% often traces to actual motor "
            "total impulse/thrust curve differing from the nominal manufacturer curve — motors "
            "have real lot-to-lot variance, which is exactly why Stage 2's Monte Carlo applies a "
            "thrust-curve tolerance band rather than trusting the nominal curve as exact."
        )
    if abs(descent_err) > 5.0:
        causes.append(
            f"Descent rate error of {abs(descent_err):.1f}% usually means the parachute's "
            "effective Cd*S in flight differs from the packed/rigged assumption — reefing, "
            "canopy oscillation, or a different porosity than modeled."
        )
    if not causes:
        causes.append("All metrics within normal V&V agreement — no dominant error source flagged.")
    return causes


def run_stage5(simulated: FlightLogRecord, actual: FlightLogRecord,
               acceptable_error_pct: float = ACCEPTABLE_ERROR_PCT) -> ValidationResult:
    apogee_err = _pct_error(simulated.apogee_m, actual.apogee_m)
    velocity_err = _pct_error(simulated.max_velocity_m_s, actual.max_velocity_m_s)
    descent_err = _pct_error(simulated.descent_rate_m_s, actual.descent_rate_m_s)

    within = all(abs(e) <= acceptable_error_pct for e in (apogee_err, velocity_err, descent_err))
    causes = _diagnose(apogee_err, velocity_err, descent_err)

    return ValidationResult(
        simulated=simulated,
        actual=actual,
        apogee_error_pct=apogee_err,
        velocity_error_pct=velocity_err,
        descent_rate_error_pct=descent_err,
        within_acceptable_error=within,
        acceptable_error_pct=acceptable_error_pct,
        likely_causes=causes,
    )
